time_step: 0.01
real_time: True
headless: True
num_trials: 100
num_memory_trials: 4
models:
  # - "qwen3-coder-480b-a35b-instruct"
  # - "gpt-4.1"
  # - "claude-3.5-sonnet"
  # - "claude-sonnet-4"
  # - "gemini-2.5-pro"
  # - "gemini-2.5-flash"
  - "deepseek-v3.1"
  # - "devstral-small-2507"
prompts: 
  - "Put away all the items into the shelf."
  - "Swap the mug and the cube in the shelf."
conditions: 
  - task_index: 0
    value:
      location:
        Kitchen Shelf:
          place_positions:
            - top
            - middle
            - bottom
    condition: "occupied_by"
    targets:
      - "mug"
      - "cube"
      - "box"
  - task_index: 1
    value: 
      location:
        Kitchen Shelf:
          place_positions:
            - top
            - middle
            - bottom
    condition: "swap"
    targets:
      - "mug"
      - "cube"