num_iterations: 5
models:
  - "gpt-4.1"
  - "claude-3.5-sonnet"
  - "qwen3-coder-480b-a35b-instruct"
prompts: 
  - "Put away all the items into the shelf."
  - "Swap the mug and the cube in the shelf."
conditions: 
  - task_index: 0
    value:
      location:
        shelf:
          place_positions:
            - top
            - middle
            - bottom
    condition: "occupied_by"
    targets:
      - "mug"
      - "cube"
      - "box"
  - task_index: 1
    value: 
      location:
        shelf:
          place_positions:
            - top
            - middle
            - bottom
    condition: "swap"
    targets:
      - "mug"
      - "cube"